#!/usr/bin/env python3
"""Regenerate worked example blocks and splice them into latex/master.tex.

This is the single, repeatable procedure for (re)building the example blocks --
no hand-written one-off splicing. Each block is generated by build_example_block
and replaces the existing mdframed found under a locating marker in master.tex.

Usage:
    python3 place_example_blocks.py            # rebuild all registered blocks
    python3 place_example_blocks.py general    # rebuild only the named block(s)

A block is located by a unique substring that appears on the line introducing it
(its subsection line or its \\textbf{Example (...)} line). We then replace the
first \\begin{mdframed}...\\end{mdframed} at or after that marker.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MASTER = os.path.join(HERE, 'latex', 'master.tex')
sys.path.insert(0, HERE)
import build_example_block as B

# Registry: key -> (display name, M1, R1, M2, R2, locating-substring).
# The locating substring must uniquely identify the block's intro line.
# NOTE: rs-referencing blocks are NOT here yet -- they need the rs token
# The two rs-referencing blocks pass a PRE-CALCULATED radius (a plain number),
# not an rs token. Each is rs * <factor> computed at full precision up front:
#   staticmass_rs : R1 = rs(2e30) * 1.00001  (just above rs; exact rs is the
#                   degenerate GTD=0 limit, so we approximate the Schwarzschild
#                   condition by an arbitrarily small increment above rs)
#   staticmass_43 : R1 = rs(1e30) * 4/3      (the GTD=1/2 point; not degenerate)
BLOCKS = {
    'staticmass_43': ('Static Mass',     '1e30',
                      '1980.3094050983108004958743073026861565296409939776',
                      '1e30', '1e8',
                      r'\subsection{Case 1:'),
    'staticmass_rs': ('Static Mass',     '2e30',
                      '2970.4938122885426754058188990686387750868094355814',
                      '2e30', '7e8',
                      r'\subsection{Case 2:'),
    'staticmass2':  ('Static Mass',      '2e30', '3e3',  '2e30', '7e8',
                     r'\subsection{Case 3:'),
    'staticradius': ('Static Radius',    '1e30', '1e8',  '1e24', '1e8',
                     r'\subsection{Case 4:'),
    'density':      ('Constant Density', '1e30', '1e8',  '1e27', '1e7',
                     r'\subsection{Case 5:'),
    'inertia':      ('Constant Inertia', '1e32', '1e7',  '1e30', '1e8',
                     r'\subsection{Case 6:'),
    'general':      ('General Case',     '1e20', '2e-7', '1e30', '1e7',
                     r'\subsection{Case 7:'),
    'classical':    ('Classical',        '8',    '2',    '1',    '1',
                     r'\subsection{Case 8:'),
}


def splice_one(lines, marker, block_text):
    """Replace the first mdframed at/after the line containing `marker`."""
    try:
        m = next(i for i, l in enumerate(lines) if marker in l)
    except StopIteration:
        raise SystemExit(f'marker not found: {marker!r}')
    b = next(i for i in range(m, len(lines)) if lines[i].strip() == r'\begin{mdframed}')
    e = next(i for i in range(b, len(lines)) if lines[i].strip() == r'\end{mdframed}')
    lines[b:e + 1] = [block_text]
    return b + 1, e + 1


def main():
    keys = sys.argv[1:] or list(BLOCKS)
    for k in keys:
        if k not in BLOCKS:
            raise SystemExit(f'unknown block {k!r}; known: {", ".join(BLOCKS)}')

    lines = open(MASTER).readlines()
    # Splice bottom-up so earlier indices stay valid.
    located = []
    for k in keys:
        name, M1, R1, M2, R2, marker = BLOCKS[k]
        m = next((i for i, l in enumerate(lines) if marker in l), None)
        if m is None:
            raise SystemExit(f'marker not found for {k!r}: {marker!r}')
        located.append((m, k))
    located.sort(reverse=True)

    for _, k in located:
        name, M1, R1, M2, R2, marker = BLOCKS[k]
        block = B.build_block(name, M1, R1, M2, R2).rstrip('\n') + '\n'
        b, e = splice_one(lines, marker, block)
        print(f'spliced {k:14s} -> {b}..{e}  ({name})')

    open(MASTER, 'w').writelines(lines)
    print(f'wrote {MASTER}')


if __name__ == '__main__':
    main()
